#!/usr/bin/env bash
# ==============================================================================
# One-time (idempotent) instance bootstrap:
#   1. mount persistent block storage
#   2. install system dependencies (ffmpeg, python, build tools)
#   3. clone/update the repository from GitHub
#   4. create a venv ON THE BLOCK STORAGE and install the project + CUDA torch
#   5. install the official TRIBE v2 package
#   6. write the persistent env file consumed by run_pipeline.sh
#
# Env in:  REPO_URL, BRANCH, MOUNT_POINT, BLOCK_LABEL
# ==============================================================================
set -euo pipefail

REPO_URL="${REPO_URL:?REPO_URL is required}"
BRANCH="${BRANCH:-main}"
MOUNT_POINT="${MOUNT_POINT:-/mnt/ysp-data}"
CODE_DIR="/opt/ysp"
VENV="${MOUNT_POINT}/venv/ysp"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "==[bootstrap]== storage"
MOUNT_POINT="${MOUNT_POINT}" bash "${SCRIPT_DIR}/mount_storage.sh"

echo "==[bootstrap]== system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
    git ffmpeg python3.12 python3.12-venv python3-pip build-essential curl ca-certificates

echo "==[bootstrap]== GPU check"
if command -v nvidia-smi >/dev/null 2>&1; then
    nvidia-smi || true
else
    echo "WARNING: nvidia-smi not found. Use a Vultr GPU image with NVIDIA drivers," \
         "or install the CUDA driver before running TRIBE/training." >&2
fi

echo "==[bootstrap]== repository"
if [ ! -d "${CODE_DIR}/.git" ]; then
    git clone --branch "${BRANCH}" "${REPO_URL}" "${CODE_DIR}"
else
    git -C "${CODE_DIR}" fetch --all --prune
    git -C "${CODE_DIR}" checkout "${BRANCH}"
    git -C "${CODE_DIR}" pull --ff-only
fi

echo "==[bootstrap]== python environment (on persistent storage)"
if [ ! -x "${VENV}/bin/python" ]; then
    python3.12 -m venv "${VENV}"
fi
# shellcheck disable=SC1091
source "${VENV}/bin/activate"
pip install --upgrade pip wheel

echo "==[bootstrap]== project + CUDA torch stack"
pip install -e "${CODE_DIR}"
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
pip install -r "${CODE_DIR}/requirements-gpu.txt"

echo "==[bootstrap]== official TRIBE v2"
bash "${CODE_DIR}/scripts/install_tribe.sh"

echo "==[bootstrap]== persistent env file"
cat > "${MOUNT_POINT}/ysp.env" <<EOF
# Auto-generated by bootstrap.sh — all state lives on the block storage.
export YSP_ENV=production
export YSP_DATA_DIR=${MOUNT_POINT}/data
export YSP_RAW_DIR=${MOUNT_POINT}/data/raw
export YSP_PROCESSED_DIR=${MOUNT_POINT}/data/processed
export YSP_CACHE_DIR=${MOUNT_POINT}/cache
export YSP_MODELS_DIR=${MOUNT_POINT}/models
export YSP_DATABASE_URL=sqlite:///${MOUNT_POINT}/ysp.db
export TRIBE_CACHE_DIR=${MOUNT_POINT}/cache/tribe
export TRIBE_DEVICE=cuda
export YSP_DEVICE=cuda
export YSP_CODE_DIR=${CODE_DIR}
export YSP_VENV=${VENV}
EOF

echo "==[bootstrap]== apply database migrations"
# shellcheck disable=SC1090
source "${MOUNT_POINT}/ysp.env"
( cd "${CODE_DIR}/backend" && alembic upgrade head )

echo "==[bootstrap]== complete."
