"""add subtitle_path and validation to videos

Revision ID: 1fed7dcd8cf6
Revises: 2faa74db68af
Create Date: 2026-07-05 01:08:24.723056
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fed7dcd8cf6"
down_revision: str | None = "2faa74db68af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtitle_path", sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column("validation", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_column("validation")
        batch_op.drop_column("subtitle_path")

    # ### end Alembic commands ###
