"""initial schema

Revision ID: 2faa74db68af
Revises:
Create Date: 2026-07-05 00:16:35.571485
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2faa74db68af"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("run_dir", sa.String(length=512), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("total_epochs", sa.Integer(), nullable=True),
        sa.Column("best_metric", sa.Float(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
    )
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_experiments_name"), ["name"], unique=False)

    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("checkpoint_path", sa.String(length=512), nullable=False),
        sa.Column("onnx_path", sa.String(length=512), nullable=True),
        sa.Column("torchscript_path", sa.String(length=512), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("target_stats", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("name", "version", name="name_version"),
    )
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_models_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_models_name"), ["name"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("youtube_id", sa.String(length=32), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("title", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("channel", sa.String(length=256), nullable=True),
        sa.Column("channel_id", sa.String(length=64), nullable=True),
        sa.Column("subscriber_count", sa.BigInteger(), nullable=True),
        sa.Column("view_count", sa.BigInteger(), nullable=True),
        sa.Column("like_count", sa.BigInteger(), nullable=True),
        sa.Column("comment_count", sa.BigInteger(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("upload_date", sa.DateTime(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("video_path", sa.String(length=512), nullable=True),
        sa.Column("audio_path", sa.String(length=512), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=512), nullable=True),
        sa.Column("frames_dir", sa.String(length=512), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("brain_status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_videos_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.create_index("ix_videos_channel_id", ["channel_id"], unique=False)
        batch_op.create_index("ix_videos_status", ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_youtube_id"), ["youtube_id"], unique=True)

    op.create_table(
        "embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("producer", sa.String(length=128), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("shape", sa.JSON(), nullable=False),
        sa.Column("dtype", sa.String(length=16), nullable=False),
        sa.Column("num_timesteps", sa.Integer(), nullable=True),
        sa.Column("num_features", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_embeddings_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
        sa.UniqueConstraint("video_id", "kind", "producer", name="video_kind_producer"),
    )
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_embeddings_video_id"), ["video_id"], unique=False)

    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("targets", sa.JSON(), nullable=False),
        sa.Column("intervals", sa.JSON(), nullable=False),
        sa.Column("uncertainty", sa.JSON(), nullable=False),
        sa.Column("virality_score", sa.Float(), nullable=True),
        sa.Column("confidence_level", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_predictions_model_id_models")
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_predictions_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_predictions_model_id"), ["model_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_predictions_video_id"), ["video_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_predictions_virality_score"), ["virality_score"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_predictions_virality_score"))
        batch_op.drop_index(batch_op.f("ix_predictions_video_id"))
        batch_op.drop_index(batch_op.f("ix_predictions_model_id"))

    op.drop_table("predictions")
    with op.batch_alter_table("embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_embeddings_video_id"))

    op.drop_table("embeddings")
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_videos_youtube_id"))
        batch_op.drop_index("ix_videos_status")
        batch_op.drop_index("ix_videos_channel_id")

    op.drop_table("videos")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_models_name"))
        batch_op.drop_index(batch_op.f("ix_models_is_active"))

    op.drop_table("models")
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_experiments_name"))

    op.drop_table("experiments")
    # ### end Alembic commands ###
